# Generated by Django 4.2.28 on 2026-02-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_tags_category_note_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='info', max_length=25),
        ),
    ]
